"Applied fix from trunk for revision: 1741925  " ------------------------------------------------------------------------ r1741925 | jleroux | 2016-05-02 09:35:38 +0200 (lun. 02 mai 2016) | 16 lignes
A patch from Ingo Wolfmayr for "Agreement Search List requires partyIdFrom/partyIdTo or fails" - https://issues.apache.org/jira/browse/OFBIZ-7030

How tot test!
Create a new agreement and fill the following fields:

    partyTo (for ex. DemoCustomer)
    Role Type Id From (for ex. Client)
    Role Type Id To(for ex. Bill-to customer)
    Agreement Type ID (for ex. Sales)
    Description: test

error: Error in form [ListAgreements] calling service with name [getPartyNameForDate]: org.ofbiz.service.ServiceValidationException: The following required parameter is missing: [getPartyNameForDate.partyId]java.lang.IllegalArgumentException: Error in form [ListAgreements] calling service with name [getPartyNameForDate]: org.ofbiz.service.ServiceValidationException: The following required parameter is missing: [getPartyNameForDate.partyId]

I create a generic agreement (from company to all customers with no specific agreements) - I could not access it after creation.

I added a not-empty check.
------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release15.12@1741926 13f79535-47bb-0310-9956-ffa450edef68