Someone working in different timezone(for ex: PST or any other) should receive following error message while update ProductAssoc record. This patch will fix the issue, Thanks Scott for the tip.
2010-11-15 03:11:14,497 (http-0.0.0.0-8443-1) [     ControlServlet.java:144:INFO ] [[[UpdateProductAssoc] Request Begun, encoding=[UTF-8]- total:0.0,since last(Begin):0.0]]
2010-11-15 03:11:14,735 (http-0.0.0.0-8443-1) [   GenericDelegator.java:1368:ERROR] 
---- exception report ----------------------------------------------------------
Failure in store operation for entity [ProductAssoc]: org.ofbiz.entity.GenericEntityNotFoundException: Tried to update an entity that does not exist.. Rolling back transaction.
Exception: org.ofbiz.entity.GenericEntityNotFoundException
Message: Tried to update an entity that does not exist.
---- stack trace ---------------------------------------------------------------
org.ofbiz.entity.GenericEntityNotFoundException: Tried to update an entity that does not exist.
org.ofbiz.entity.datasource.GenericDAO.singleUpdate(GenericDAO.java:282)
org.ofbiz.entity.datasource.GenericDAO.customUpdate(GenericDAO.java:214)
org.ofbiz.entity.datasource.GenericDAO.update(GenericDAO.java:208)
org.ofbiz.entity.datasource.GenericHelperDAO.store(GenericHelperDAO.java:171)
org.ofbiz.entity.GenericDelegator.store(GenericDelegator.java:1353)
org.ofbiz.entity.GenericDelegator.store(GenericDelegator.java:1316)
org.ofbiz.entity.GenericValue.store(GenericValue.java:129)
org.ofbiz.product.product.ProductEvents.updateProductAssoc(ProductEvents.java:372)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
java.lang.reflect.Method.invoke(Method.java:597)
org.ofbiz.webapp.event.JavaEventHandler.invoke(JavaEventHandler.java:92)
org.ofbiz.webapp.event.JavaEventHandler.invoke(JavaEventHandler.java:78)
org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:634)
org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:380)
org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:227)
org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:90)
javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:269)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:852)
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
java.lang.Thread.run(Thread.java:619)
--------------------------------------------------------------------------------

2010-11-15 03:11:14,736 (http-0.0.0.0-8443-1) [    TransactionUtil.java:344:INFO ] [TransactionUtil.rollback] transaction rolled back
2010-11-15 03:11:14,737 (http-0.0.0.0-8443-1) [    TransactionUtil.java:269:WARN ] [TransactionUtil.commit] Not committing transaction, status is No Transaction (6)

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1035080 13f79535-47bb-0310-9956-ffa450edef68