"Applied fix from trunk framework for revision: 1867099" ------------------------------------------------------------------------ r1867099 | jleroux | 2019-09-18 09:29:18 +0200 (mer. 18 sept. 2019) | 17 lignes
Fixed: Error in log when looking for parties at partymgr/control/main
(OFBIZ-11201)

There is this a (long stack trace) error in log (only), mostly

java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
at org.apache.ofbiz.base.util.string.UelFunctions.getSize(UelFunctions.java:318)

I did not notice any other effect, so the fix only cleans the log.

It's actually an issue in ListParty grid with this line:
<set field="userLoginSize" value="${util:size(logins)}" type="Integer"/>

This fixes it by replacing by 
<set field="userLoginSize" value="${groovy:logins.size()}"/>


------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release16.11@1867102 13f79535-47bb-0310-9956-ffa450edef68