Revert r945037, because I found it's not right when going back from  logout -> forgot password, I got this error message
org.ofbiz.webapp.control.RequestHandlerException: Unknown request [authview]; this request does not exist or cannot be called directly.

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@945042 13f79535-47bb-0310-9956-ffa450edef68