"Applied fix from trunk for revision: 1763085  " (path conflict handld by hand) ------------------------------------------------------------------------ r1763085 | jleroux | 2016-10-02 19:12:37 +0200 (dim. 02 oct. 2016) | 16 lignes
Fixes: Can't find resource for bundle
(OFBIZ-8336)

When going for example to EditProductContent (Product --> Content) 
the following error message appears:
2016-09-27 20:02:40,822 |http-nio-8444-exec-7 |UtilProperties |I| null
java.util.MissingResourceException: Can't find resource for bundle 
org.apache.ofbiz.base.util.UtilProperties$UtilResourceBundle, 
key FieldDescription.sequenceNum

jleroux: this has not been handled right from start and in several changes
later. Rather than throwing an exception in UtilProperties.getMessage() it's 
better to check if the bundle contains the key and else to log info


Thanks: Ingo Wolfmayr for report and Rohit Koushal for research
------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release13.07@1763087 13f79535-47bb-0310-9956-ffa450edef68