"Applied fix from trunk for revision: 1400393" ------------------------------------------------------------------------ r1400393 | jleroux | 2012-10-20 10:59:40 +0200 (sam., 20 oct. 2012) | 17 lines
A patch from Tom Burns "Error is comming in HR's recruitment  Tab  " https://issues.apache.org/jira/browse/OFBIZ-5056

I am getting an error(null Pointer Exception) in HR module when i am testing some functionallities.
I followed some steps in my testing.
Step 1:-Cleck on Recruitment tab and also click on "New job Requisition".Fill the data and create the record.
Steps 2:-click on sub tap "Internal Job Posting" and then click on "New internal Job Posting" Button on find Internal job posting page. Create the record from require data
Step3:-Again click "Internal Job Posting" sub tab. and find the created Internal Job Posting record.
You find operastion give the Error Massage
:ERROR MESSAGE:
org.ofbiz.widget.screen.ScreenRenderException: Error rendering screen component://common/widget/CommonScreens.xml#FindScreenDecorator: java.lang.NullPointerException (null)
You also check Job Interview and Approve sub tab
I have sent this mail to jacopo Le but Issue is not resolve till date
Please solve this issuse. I Am waiting for ur responce APAS
Thanks
Dhiraj Gupta


------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release11.04@1400398 13f79535-47bb-0310-9956-ffa450edef68