"Applied fix from trunk for revision: 1506269" ------------------------------------------------------------------------ r1506269 | jleroux | 2013-07-23 22:44:10 +0200 (mar. 23 juil. 2013) | 17 lignes
A patch from Petr Pytelka for "upload content at party profile is not working" https://issues.apache.org/jira/browse/OFBIZ-5202

I tried to upload content at party profile screen with purpose "Logo Image URL" and Is public "YES" but i got the following exception
---- exception report ----------------------------------------------------------
ERROR: Could not complete the Create Content Alternative URLs. [file:/media/68C2E6E0C2E6B18C/Work/Developers_foundation/Workspace/OFBiz/ofbiz/applications/content/script/org/ofbiz/content/content/ContentServices.xml#createContentAlternativeUrl] process [problem invoking the [createContent] service with the map named [contentCtx] containing [{dataResourceId=10001, statusId=CTNT_IN_PROGRESS, localeString=en_US, userLogin=[GenericEntity:UserLogin][createdStamp,2013-05-23 12:19:58.0(java.sql.Timestamp)][createdTxStamp,2013-05-23 12:19:58.0(java.sql.Timestamp)][currentPassword,null()][disabledDateTime,null()][enabled,N(java.lang.String)][externalAuthId,null()][hasLoggedOut,null()][isSystem,Y(java.lang.String)][lastCurrencyUom,null()][lastLocale,null()][lastTimeZone,null()][lastUpdatedStamp,2013-05-23 12:19:58.0(java.sql.Timestamp)][lastUpdatedTxStamp,2013-05-23 12:19:58.0(java.sql.Timestamp)][partyId,null()][passwordHint,null()][requirePasswordChange,null()][successiveFailedLogins,null()][userLdapDn,null()][userLoginId,system(java.lang.String)], locale=en_US}]: The following required parameter is missing: [IN] [createContentRole.partyId]]
Exception: org.ofbiz.service.ServiceValidationException
Message: The following required parameter is missing: [IN] [createContentRole.partyId]

jleroux: 
I see no reasons to not move the lines
<!-- Party for System UserLogin Account - just in case logic depends on it -->
<Party partyId="system" partyTypeId="PERSON"/>
<Person partyId="system" firstName="System" lastName="Account"/>

from UserDemoData.xml to SecurityPermissionSeedData.xml

This patch  allows to load data for party "system" when load-extseed is called.
------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release11.04@1533342 13f79535-47bb-0310-9956-ffa450edef68