"Applied fix from trunk for revision: 1334201" ------------------------------------------------------------------------ r1334201 | jleroux | 2012-05-04 23:46:25 +0200 (ven., 04 mai 2012) | 9 lines
A slightly modified patch from Ankit Jain "Error on View Facility Inventory Items Details Page" https://issues.apache.org/jira/browse/OFBIZ-4851

Error on https://demo-trunk.ofbiz.apache.org:8443/facility/control/ViewFacilityInventoryItemsDetails Page, when you select Report Type - "By Inventory Item" or "By Product" its throwing error.

org.ofbiz.widget.screen.ScreenRenderException: Error rendering screen component://common/widget/CommonScreens.xml#GlobalDecorator: java.lang.IllegalArgumentException: Return value from use-when condition eval was not a Boolean: null [null] on the field inventoryItemId of form ListFacilityInventoryItemsDetailsByItem (Return value from use-when condition eval was not a Boolean: null [null] on the field inventoryItemId of form ListFacilityInventoryItemsDetailsByItem)

jleroux: I supposed it was related to recent changes on scripts language, but was not sure. So I searched for ${bsh:* type="Boolean"/> and found some others of the same kind: in UpdateProductFacilityLocations, FindProject, sprintBacklogListItems forms and more in scrumForms.xml. I tried with UpdateProductFacilityLocations & FindProject but surprisingly did not reproduce the problem. At this stage I gave up...

Sligth changes from Ankit's patch: I simply used real ' instead of &quot; and reformatted to make things more legible
------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release12.04@1334338 13f79535-47bb-0310-9956-ffa450edef68