"Applied BY HAND fix from trunk framework for revision: 1799859 + 1799860" ------------------------------------------------------------------------ Fixed: Error running the simple-method: Error running groovy script (OFBIZ-9432)
Steps to reproduce the error:
Add producs to cart (i.e. 2 x RoundGizmo) 
-> [Quick Checkout] 
-> Checkout Without Login: Quick Checkout 
-> Basic Information: fill in required fields 
-> Continue 

Error: unable to resolve class CartItemModifyException

jleroux: Groovy needs the complete path to CartItemModifyException
There were 2 cases, I have also removed the trailing semicolons

Thanks: Daniel Coric for report
------------------------------------------------------------------------

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release16.11@1799862 13f79535-47bb-0310-9956-ffa450edef68